### ISSUE TITLE
Compatibility issue with AntennaRange

### ISSUE THREAD

**Issue by TMarkos** [TMarkos/ESLDBeacons#72]
http://forum.kerbalspaceprogram.com/threads/91582-1-0-2-ESLD-Jump-Beacons-Dev-0-6-2015-05-25/page18

Probably the activation that messes with it, have to install both and have a look.

**Comment by Katalliaan** [comment]
I had a chance to look into the code of both mods myself. I can confirm it's related to both mods using the part state of an antenna for their own purposes. Here's the relevant section of AntennaRange's code (from ProtoAntennaRelay.cs):

    public override bool CanTransmit()
		{
			PartStates partState = (PartStates)this.protoPart.state;
			if (partState == PartStates.DEAD || partState == PartStates.DEACTIVATED)
			{
				Tools.PostDebugMessage(string.Format(
					"{0}: {1} on {2} cannot transmit: {3}",
					this.GetType().Name,
					this.Title,
					this.vessel.vesselName,
					Enum.GetName(typeof(PartStates), partState)
				));
				return false;
			}
			return base.CanTransmit();
		}

However, since the hailer doesn't require control over the vessel to activate, its GUI can be dragged mostly off-screen and left open as a workaround.
